# Constants

In [1]:
import tensorflow as tf

## Tensor

- Deeplearning framework는 기본적으로 Tensor를 다루는 도구다.
    - [Tensor](https://www.google.com/search?q=Tensor&newwindow=1&sxsrf=AOaemvLxCRvi46j5dRtWwY8K6ssvkpF48A:1641452781782&source=lnms&tbm=isch&sa=X&ved=2ahUKEwin2eSPyJz1AhXNdd4KHWzUAd8Q_AUoAXoECAIQAw&biw=1440&bih=820&dpr=2)


- Tensor를 다룰 때 가장 중요한 것! 

  ${\rightarrow} \ $ **SHAPE !!!**
  
 (해보면 알겠지만, 제일 에러 많이 나는 이유, 제일 헷갈리는 것, 개발할 때 우리가 이론을 알아야 하는 이유, 함수들의 설정값을 확인해야하는 이유)
 
 

## Tensor 생성

In [2]:
li = [1, 2, 3]
type(li)

list

우리가 생성하는 것은 `tf.Tensor` 데이터!

**항상 체크 해야 할 것 !**
 - shape
 - dtype (데이터 타입이 같아야 연산이 가능합니다.)

<h4> Constant (상수)</h4>

- **```tf.constant()```**

    - 기존의 데이터 타입을 Tensor로 변환시켜줌
    - list -> Tensor
    - tuple -> Tensor
    - Array -> Tensor

In [4]:
li_ten = tf.constant([1, 2, 3])
li_ten

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [5]:
li_ten_f = tf.constant([1., 2., 3.])
li_ten_f

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [6]:
tu_ten = tf.constant(((1, 2, 3), (1, 2, 3)), name="sample")
tu_ten

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]])>

In [8]:
import numpy as np
arr = np.array([1., 2., 3.])#, dtype='float64')
arr_ten = tf.constant(arr)
arr_ten

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

#### 잠깐 옆으로 새서...
* double precision : 64bits
* single precision : 32bits
* half precision   : 16bits

### Numpy array 추출

-  `.numpy()`

In [9]:
arr_ten.numpy(), type(arr_ten.numpy())

(array([1., 2., 3.]), numpy.ndarray)

In [10]:
li_ten.numpy(), type(li_ten.numpy())

(array([1, 2, 3]), numpy.ndarray)

In [12]:
# 구조적으로 이상한 형태인 것들은 변환 안됨
not_a_matrix = [[1,2,3], [4, 5], [6, 7, 8]]
tf.constant(not_a_matrix)

ValueError: Can't convert non-rectangular Python sequence to Tensor.

### shpae, dtype 항상 체크!!

- `.shape`
- `.dtype`

In [16]:
li_ten, tu_ten

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [1, 2, 3]])>)

In [13]:
li_ten.shape, tu_ten.shape

(TensorShape([3]), TensorShape([2, 3]))

In [14]:
arr_ten.dtype, li_ten.dtype

(tf.float64, tf.int32)

In [15]:
# 1번 케이스
tf.matmul(li_ten, tu_ten)

#  In[0] and In[1] has different ndims: [3] vs. [2,3] [Op:MatMul] name
# dim이 맞지 않아 연산 불가

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} In[0] and In[1] has different ndims: [3] vs. [2,3] [Op:MatMul] name: 

In [17]:
# 2번 케이스
tf.matmul(tu_ten, li_ten)
# rank 수가 맞지 않아 연산 불가

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} In[0] and In[1] has different ndims: [2,3] vs. [3] [Op:MatMul] name: 

rank 수 확인 명령어 `.ndim`

In [18]:
print(li_ten.ndim)
print(tu_ten.ndim)

1
2


In [20]:
arr_ten, li_ten

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>)

In [19]:
# 3번 케이스
arr_ten * li_ten
# dtype이 다르면 연산 불가

InvalidArgumentError: cannot compute Mul as input #1(zero-based) was expected to be a double tensor but is a int32 tensor [Op:Mul] name: 

### 데이터 타입 컨트롤하는 방법
  - `tf.cast`

In [21]:
# 미리 지정해주거나
tensor = tf.constant([1, 2, 3], dtype=tf.float32)
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [22]:
# tf.cast를 사용. 다만, 많은 경우 미리 데이터타입을 정리해둘 수 있다.
tf.cast(tensor, dtype=tf.int16)

<tf.Tensor: shape=(3,), dtype=int16, numpy=array([1, 2, 3], dtype=int16)>

#### 간단 퀴즈 

아래 코드를 에러 없이 실행 하시오. 

In [23]:
arr_ten, li_ten

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>)

In [21]:
arr_ten * li_ten

InvalidArgumentError: cannot compute Mul as input #1(zero-based) was expected to be a double tensor but is a int32 tensor [Op:Mul]

------

In [25]:
tf.cast(arr_ten, dtype=tf.int32) * li_ten

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9])>

In [26]:
arr_ten * tf.cast(li_ten, dtype=tf.float64) 

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 4., 9.])>

### 특정 값의 Tensor 생성

 - `tf.ones`
 - `tf.zeros`
 - `tf.range`


In [27]:
tf.ones(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [28]:
tf.zeros((2, 5), dtype="int32")

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])>

In [29]:
tf.range(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [30]:
tf.range(1, 11)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])>

####  간단 퀴즈

**n 을 입력하면 첫항이 1이고 공비가 2인 등비수열을 생성하는 함수를 만드시오** 
(이 때 결과값은 tf.Tensor 데이터이고, 데이터 타입은 tf.int32)

$$
n = 10 \ 일 때 \\ \\
(1, 2, 4, 8, 16, 32, 64, 128, 256, 512)
$$

In [35]:
def geometric_sequence(n):
    r = tf.range(n, dtype = 'int32')
    s = tf.ones(n, dtype = tf.int32) * 2
    return s ** r

In [36]:
print(geometric_sequence(10))

tf.Tensor([  1   2   4   8  16  32  64 128 256 512], shape=(10,), dtype=int32)


-----

<h4> Random Value(난수)</h4>

- 무작위 값을 생성할 때 필요. 
- Noise를 재현 한다거나, test를 한다거나 할 때 많이 사용됨 
- 데이터 타입은 상수형태로 반환됨

**`tf.random`** 에 구현 되어 있음. 

  - `tf.random.normal`
      - Gaussian Normal Distribution
      
  - `tf.random.uniform`
      - Uniform Distribution
      
> 이렇게나 많습니다! [LINK](https://www.tensorflow.org/api_docs/python/tf/random)

In [37]:
shape = (3, 3)

In [38]:
tf.random.normal(shape)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.40852472,  1.7240304 , -0.97972363],
       [ 0.22779289,  0.03457008, -1.0823519 ],
       [ 0.36655924, -2.6770525 , -0.2133269 ]], dtype=float32)>

- tf.random.uniform
    - TensorFlow에서 Uniform Distribution

In [62]:
tf.random.uniform(shape)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.4063989 , 0.16350043, 0.49475944],
       [0.41444743, 0.7097274 , 0.43024313],
       [0.8637649 , 0.6725483 , 0.09786201]], dtype=float32)>

* **Random seed 관리 하기!!!**

   - Random value로 보통 가중치를 초기화 
   - 이외에도 학습과정에서 Random value가 많이 사용됨. 
   - 이를 관리 안해주면, 자신이 했던 작업이 동일하게 복구 또는 재현이 안됨!!! 
 
 
- **`tf.random.set_seed({seed_number})`**

 
**=> 항상 Random seed를 고정해두고 개발 한다!!!** 
   
   (주의 할 점은 해당 개발물에 사용되는 난수가 모두 TensorFlow에서 생성된것이 아닐 수 있다는 것이다.) 

In [39]:
seed = 7777 # 아무 숫자나 설정

In [40]:
tf.random.set_seed(seed)
a = tf.random.uniform([1])
b = tf.random.uniform([1])
print(a, b, sep="\n")

tf.Tensor([0.959749], shape=(1,), dtype=float32)
tf.Tensor([0.8677443], shape=(1,), dtype=float32)


In [41]:
a = tf.random.uniform([1])
b = tf.random.uniform([1])
print(a, b, sep="\n")

tf.Tensor([0.22878075], shape=(1,), dtype=float32)
tf.Tensor([0.87772965], shape=(1,), dtype=float32)


In [42]:
tf.random.set_seed(seed)
a = tf.random.uniform([1])
b = tf.random.uniform([1])
print(a, b, sep="\n")

tf.Tensor([0.959749], shape=(1,), dtype=float32)
tf.Tensor([0.8677443], shape=(1,), dtype=float32)
