# Variable

In [1]:
import tensorflow as tf

<h4> Variable (변수)</h4>

- 미지수, 가중치를 정의할 때 사용
- 직접 사용할 일이 많지는 않음

- 변수 정의는 변수 생성 + 초기화

In [5]:
tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])
arr = np.array([[1, 2], [3, 4]])
li = [[1, 2], [3, 4]]

te_var = tf.Variable(tensor)
arr_var = tf.Variable(arr)
li_var = tf.Variable(li)

print(te_var)
print(arr_var)
print(li_var)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int64, numpy=
array([[1, 2],
       [3, 4]])>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>


2022-01-14 23:18:07.999951: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


- Constant와 같이 기본 속성값이 들어있음. 

In [6]:
print("Shape: ", te_var.shape)
print("DType: ", te_var.dtype)
print("As NumPy: ", te_var.numpy)

Shape:  (2, 2)
DType:  <dtype: 'float32'>
As NumPy:  <bound method BaseResourceVariable.numpy of <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>>


### 변수는 기존 텐서의 메모리를 재사용하여 텐서를 재할당 할 수 있다. 


In [3]:
a = tf.Variable([2.0, 3.0])
print("First : ", a, "\n")

a.assign([1, 2]) # .assign : 형식은 동일하지만 값은 다르게 할당가능(기존 dtype을 따른다)
print("Second : ", a, "\n")


First :  <tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)> 

Second :  <tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)> 



In [4]:
# 기존 메모리의 크기와 다르면 할당 할 수 없음! 
a.assign([1.0, 2.0, 3.0]) 

ValueError: Cannot assign value to variable ' Variable:0': Shape mismatch.The variable shape (2,), and the assigned value shape (3,) are incompatible.