# Tensor 연산

In [1]:
import tensorflow as tf

아래의 기본 연산은 특수 메서드를 이용하여 연산자 오버로딩이 되어 있으므로 그냥 연산자 기호를 사용하는게 가능!

* `tf.add`: 덧셈
* `tf.subtract`: 뺄셈
* `tf.multiply`: 곱셈
* `tf.divide`: 나눗셈
* `tf.pow`: n-제곱
* `tf.negative`: 음수 부호


In [2]:
a = tf.range(6, dtype=tf.int32)   
b = 2 * tf.ones(6, dtype=tf.int32)

# 원래는 이렇게 쓰는게 원칙이지만
tf.add(a, b)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7])>

In [3]:
# 연산자 기호를 써도 자동으로 tensorflow의 연산자가 불러와져서 계산이 가능하다
a + b

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7])>

**여러가지 연산**

* `tf.abs`: 절대값
* `tf.sign`: 부호
* `tf.round`: 반올림
* `tf.ceil`: 올림
* `tf.floor`: 내림
* `tf.square`: 제곱
* `tf.sqrt`: 제곱근
* `tf.maximum`: 두 텐서의 각 원소에서 최댓값만 반환.
* `tf.minimum`: 두 텐서의 각 원소에서 최솟값만 반환.
* `tf.cumsum`: 누적합
* `tf.cumprod`: 누적곱


In [4]:
tf.maximum(a, b)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5])>

#### Axis 이해하기

    - 가장 바깥에서부터 axis 0 ~ 안쪽으로 갈수록 깊어짐

In [5]:
rank_2 = tf.random.normal((3, 3))

In [6]:
rank_2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.1264825 , -0.7998125 , -0.10860794],
       [-0.55456793, -0.9415161 ,  1.4888653 ],
       [-1.0108343 , -0.25185886,  0.7038034 ]], dtype=float32)>

In [7]:
rank_2[0]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.1264825 , -0.7998125 , -0.10860794], dtype=float32)>

In [8]:
rank_2[0, 0]

<tf.Tensor: shape=(), dtype=float32, numpy=-0.1264825>

In [9]:
rank_2[0, 2]

<tf.Tensor: shape=(), dtype=float32, numpy=-0.10860794>

3차원

In [10]:
rank_3 = tf.random.normal((3, 3, 3))

In [11]:
rank_3

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[-0.06225162, -0.00844719,  0.21867406],
        [ 0.3447987 ,  1.0735847 , -1.3441112 ],
        [-0.28537107,  0.31656495, -1.0841318 ]],

       [[-1.9703488 , -0.59761894, -0.71747935],
        [ 0.54105824,  0.8884835 ,  0.8841282 ],
        [ 1.2952037 , -1.3886279 ,  0.03796454]],

       [[ 0.2295477 ,  0.06151443,  0.5404954 ],
        [ 0.11306369, -0.3695529 , -1.6911061 ],
        [-0.24765372, -1.293568  , -0.19871797]]], dtype=float32)>

In [15]:
rank_3[0,:,:]

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.06225162, -0.00844719,  0.21867406],
       [ 0.3447987 ,  1.0735847 , -1.3441112 ],
       [-0.28537107,  0.31656495, -1.0841318 ]], dtype=float32)>

In [16]:
rank_3[0,0,:]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.06225162, -0.00844719,  0.21867406], dtype=float32)>

In [17]:
rank_3[0,0,0]

<tf.Tensor: shape=(), dtype=float32, numpy=-0.062251624>

In [18]:
rank_3[1,1,2]

<tf.Tensor: shape=(), dtype=float32, numpy=0.8841282>

4차원

In [19]:
rank_4 = tf.random.normal((3, 3, 3, 3))

In [20]:
rank_4

<tf.Tensor: shape=(3, 3, 3, 3), dtype=float32, numpy=
array([[[[ 1.3476533 , -1.6493751 ,  0.74237156],
         [-2.0532904 ,  0.59781486,  1.0127076 ],
         [-0.82902676,  1.2224858 ,  0.41567424]],

        [[-1.9210554 , -1.7882466 , -0.8900931 ],
         [ 0.48074245,  0.1255022 , -0.68298066],
         [-1.2552965 , -0.08641335, -0.19060157]],

        [[ 0.19503167,  0.6262427 ,  0.2919268 ],
         [ 0.85272324,  0.871951  , -0.41366306],
         [ 1.59967   ,  0.9506366 , -1.3550029 ]]],


       [[[ 0.83070016,  0.48375598, -0.35187876],
         [ 1.7655222 , -0.27156818,  1.0460166 ],
         [-0.26112607,  0.9115955 ,  0.85805833]],

        [[-0.09209263, -0.47067025, -0.5185584 ],
         [ 0.8839786 , -1.7278656 ,  1.3847394 ],
         [-0.20813803,  0.10851022, -0.15913153]],

        [[-0.07971098,  0.5514835 ,  1.8063989 ],
         [ 0.64061797,  0.62613565, -0.97059363],
         [-2.7785544 , -0.87387204, -0.19398607]]],


       [[[ 2.0970972 ,  0.2313

In [21]:
rank_4[1, 2, 1, 2]

<tf.Tensor: shape=(), dtype=float32, numpy=-0.97059363>

**차원 축소 연산**

* `tf.reduce_mean`: 설정한 축의 평균을 구한다. 
* `tf.reduce_max`: 설정한 축의 최댓값을 구한다. 
* `tf.reduce_min`: 설정한 축의 최솟값을 구한다. 
* `tf.reduce_prod`: 설정한 축의 요소를 모두 곱한 값을 구한다. 
* `tf.reduce_sum`: 설정한 축의 요소를 모두 더한 값을 구한다. 

In [22]:
a

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5])>

In [23]:
tf.reduce_sum(a, axis=0),

(<tf.Tensor: shape=(), dtype=int32, numpy=15>,)

In [24]:
# 보통 reduce 연산자를 쓰는 경우는 차원을 축소하고 싶을 때 사용하는데
# 가끔 차원을 유지하고 싶다면 keepdims = True 옵션을 설정해주면 됨
tf.reduce_sum(a, axis=0, keepdims = True),

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([15])>,)

In [25]:
b = tf.random.normal([2, 7])
b

<tf.Tensor: shape=(2, 7), dtype=float32, numpy=
array([[-1.3459417 , -1.4972265 ,  0.02254469,  1.4149795 ,  0.02711878,
         0.46684214,  0.6199646 ],
       [-0.10508454, -0.13637061, -0.7323845 , -0.68156457,  0.05123354,
        -1.1780418 , -0.7695793 ]], dtype=float32)>

In [26]:
tf.reduce_mean(b, axis = 1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.04167407, -0.5073988 ], dtype=float32)>

In [27]:
tf.reduce_mean(b, axis = 0)

<tf.Tensor: shape=(7,), dtype=float32, numpy=
array([-0.7255131 , -0.81679857, -0.3549199 ,  0.36670744,  0.03917616,
       -0.35559982, -0.07480735], dtype=float32)>

행렬과 관련된 연산

* `tf.matmul`: 내적
* `tf.linalg.inv`: 역행렬


In [28]:
a = tf.constant([[2, 0], [0, 1]], dtype=tf.float32)
b = tf.constant([[1, 1], [1, 1]], dtype=tf.float32)
tf.matmul(a, b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [1., 1.]], dtype=float32)>

In [29]:
a = tf.constant([[2, 0], [0, 1]], dtype=tf.float32)
tf.linalg.inv(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.5, 0. ],
       [0. , 1. ]], dtype=float32)>

**🌟 크기 및 차원을 바꾸는 명령**
 (잘 사용됩니다!!)
 
이를 사용 할 때는 축을 잘 이해하고 사용하시면 좋습니다. 

* `tf.reshape`: 벡터 행렬의 크기 변환
* `tf.transpose`: 전치 연산
* `tf.expand_dims`: 지정한 축으로 차원을 추가
* `tf.squeeze`: 벡터로 차원을 축소

In [30]:
a = tf.range(6, dtype=tf.int32)      # [0, 1, 2, 3, 4, 5]
print("a     :", a, "\n")

a_2d = tf.reshape(a, (2, 3))  # 1차원 벡터는 2x3 크기의 2차원 행렬로 변환
print("a_2d  :", a_2d, "\n")

a_2d_t = tf.transpose(a_2d)   # 2x3 크기의 2차원 행렬을 3x2 크기의 2차원 행렬로 변환
print("a_2d_t:", a_2d_t, "\n")

a_3d = tf.expand_dims(a_2d, 0) # 2x3 크기의 2차원 행렬을 1x2x3 크기의 3차원 행렬로 변환
print("a_3d  :", a_3d, "\n")
''' 
딥러닝의 배치 개념(데이터를 한 묶음으로 바라볼 때)을 이용할 때 차원이 하나 더 필요하므로 
0으로 설정 시, 기존 차원의 맨 앞에 차원 하나를 더 추가해줌
3(-1)으로 설정 시, 기존 차원의 맨 마지막에 차원 하나를 더 추가해줌
'''
a_4d = tf.expand_dims(a_3d, 3) # 1x2x3 크기의 3차원 행렬을 1x2x3x1 크기의 4차원 행렬로 변환
print("a_4d  :", a_4d, "\n")
 
a_1d = tf.squeeze(a_4d)        # 1x2x3x1 크기의 4차원 행렬을 1차원 벡터로 변환
print("a_1d  :", a_1d, "\n")   
''' 
원소의 개수가 1개인 차원을 없애주는 역할
'''

a     : tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int32) 

a_2d  : tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32) 

a_2d_t: tf.Tensor(
[[0 3]
 [1 4]
 [2 5]], shape=(3, 2), dtype=int32) 

a_3d  : tf.Tensor(
[[[0 1 2]
  [3 4 5]]], shape=(1, 2, 3), dtype=int32) 

a_4d  : tf.Tensor(
[[[[0]
   [1]
   [2]]

  [[3]
   [4]
   [5]]]], shape=(1, 2, 3, 1), dtype=int32) 

a_1d  : tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32) 



**텐서를 나누거나 두 개 이상의 텐서를 합치는 명령**

* `tf.slice`: 특정 부분을 추출
* `tf.split`: 분할
* `tf.concat`: 합치기
* `tf.tile`: 복제-붙이기
* `tf.stack`: 합성
* `tf.unstack`: 분리 

In [31]:
a = tf.reshape(tf.range(12), (3, 4))
a

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [19]:
# tf.slice(input_, begin, size, name=None)
# begin : 잘라낼 부분 텐서의 시작 위치
# size : 잘라낼 부분 텐서의 크기
tf.slice(a, [0, 1], [2, 3])   # (0, 1)위치에서 (2개, 3개)만큼 뽑아낸다.

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [5, 6, 7]], dtype=int32)>

In [40]:
tf.slice(a, [1, 0],[2, 4] )

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [41]:
a1, a2 = tf.split(a, num_or_size_splits=2, axis=1)  # 가로축(axis=1)을 따라 2개로 분할 
print(a1)
print(a2)

tf.Tensor(
[[0 1]
 [4 5]
 [8 9]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  3]
 [ 6  7]
 [10 11]], shape=(3, 2), dtype=int32)


In [42]:
tf.concat([a1, a2], 1) # 가로축(axis=1)을 따라 a1, a2를 합치기

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [44]:
tf.concat([a1, a2], 0) 

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [ 2,  3],
       [ 6,  7],
       [10, 11]])>

In [43]:
tf.tile(a1, [1, 3])  # 가로축(axis=1)을 따라 3개로 복사-붙이기

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[0, 1, 0, 1, 0, 1],
       [4, 5, 4, 5, 4, 5],
       [8, 9, 8, 9, 8, 9]])>

rank가 동일한 concat과 달리 stack은 rank를 바꾸며 붙여줌

In [45]:
a3 = tf.stack([a1, a2])  # 3x2 행렬 a1, a2를 추가적인 차원으로 붙여서 2x3x2 고차원 텐서 생성
a3

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11]]])>

In [46]:
tf.unstack(a3, axis=1)  # 2x3x2 고차원 텐서를 0차원으로 풀어서 3개의 2x2 행렬 생성

[<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[0, 1],
        [2, 3]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[4, 5],
        [6, 7]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 8,  9],
        [10, 11]])>]

#### 간단 퀴즈

다음 코드를 에러 없이 실행하라. 

In [47]:
a = tf.constant(((1, 2, 3), (1, 2, 3)))
b = tf.constant([1, 2, 3])

tf.matmul(a, b)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} In[0] and In[1] has different ndims: [2,3] vs. [3] [Op:MatMul] name: 

In [48]:
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]])>

In [49]:
b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [51]:
tf.matmul(a, tf.reshape(b, (3, -1)))

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[14],
       [14]])>

In [52]:
tf.matmul(a, tf.expand_dims(b, axis = 1))

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[14],
       [14]])>

-----